[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "jupyter>=1.1.1",
    "jupyterlab>=4.3.4",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "trafilatura>=2.0.0",
]
