name: Generate Basketball Reports

on:
  # Run on push to main branch
  push:
    branches: [ main ]
  
  # Run on pull requests to main
  pull_request:
    branches: [ main ]
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run weekly on Sundays at 06:00 UTC
  schedule:
    - cron: '0 6 * * 0'

# Set permissions for GitHub token
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  generate-reports:
    runs-on: ubuntu-latest
    
    # Set environment for GitHub Pages deployment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: uv sync
    
    - name: Generate basketball reports
      run: |
        uv run run.py --group_ids 17182 18299 --season 2024
    
    - name: Upload reports as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: basketball-reports
        path: reports/
        retention-days: 30
    
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: actions/configure-pages@v5
    
    - name: Upload to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./reports
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      id: deployment
      uses: actions/deploy-pages@v4