name: Generate Basketball Reports

on:
  # Run on push to main branch
  push:
    branches: [ main ]
  
  # Run on pull requests to main
  pull_request:
    branches: [ main ]
  
  # Allow manual triggering
  workflow_dispatch:
  
  # Run weekly on Sundays at 06:00 UTC
  schedule:
    - cron: '0 6 * * 0'

jobs:
  generate-reports:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.11
    
    - name: Install dependencies
      run: uv sync
    
    - name: Generate basketball reports
      run: |
        uv run run.py --group_ids 17182 18299 --season 2024
    
    - name: Upload reports as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: basketball-reports
        path: reports/
        retention-days: 30
    
    - name: Deploy to GitHub Pages (if on main branch)
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        force_orphan: true